# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python-terraform package installation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
      with:
        repository: srinivasmunugoti/terraform_python_githubactions
        ref: 'main'
    #    token: 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

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
        cache: 'pip' # caching pip dependencies        
    - run: pip install -r requirements.txt
    - name: checking all versions
      run: |
         aws configure list
         terraform --version
         git --version

    - name: "Configure AWS Credentials" 
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        aws-access-key-id: AKIA3TDJBUERPJANR5XW
        aws-secret-access-key: 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
        
    - name: aws configure list updated
      run: aws configure list
      
    - name: present location
      run: ls -lrt
#    - name: terraform initialization
 #     run: terraform init -backend-config=backend.tfvars

      
#    - name: terraform planning
#      run: terraform plan
      
#    - name: terraform applying
#      run: terraform apply -auto-approve
   #  - name: terraform destroy
   #    run: terraform destroy -auto-approve
